### ISSUE TITLE
Please create tag or release for v1.0.0

### ISSUE THREAD

**Issue by westonganger** [andreax79/iplib.js#1]
Wanting to use this with rails-assets.org

Could you please create a tag or release for 1.0.0

**Comment by andreax79** [comment]
Done, tag added.

**Comment by westonganger** [comment]
Sorry but `1.0` is not a valid semver version so its still causing a problem with rails-assets.org, could you please tag `1.0.0`

**Comment by andreax79** [comment]
Ok, tag v1.0.0 added
