### ISSUE TITLE
[Feature Request] Convert CIDR to a list of IP addresses

### ISSUE THREAD

**Issue by serialfuzzer** [andreax79/iplib.js#2]
Could this feature be added?

Input could be 192.168.0.1/24
and output would be array of IP addresses in that range

**Comment by andreax79** [comment]
I have added the `getAllValidIp()` generator, example:

```
const c = new iplib.CIDR("192.168.0.0/24");
for (const ip of c.getAllValidIp() {
  console.log(ip);
}
```

**Comment by serialfuzzer** [comment]
Thank you @andreax79 ! :)
